version: 2.1

orbs:
  android: circleci/android@2.4.0

default-keys: &default-keys
  working_directory: ~/repo
  
jobs:
  setup:
    <<: *default-keys
    steps:
      - run:
          name: Download cc-test-reporter
          command: | 
            mkdir -p tmp
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter

  upload-test-coverage:
    environment: 
      CC_TEST_REPORTER_ID: 967f3e97d9f6a74d6a00ad70ae7b3cfae1aa3facb40d05dd13612ac5cd54cd5c

  unit-test:
    <<: *default-keys
    executor: # comes from the orb
      name: android/android-docker
      tag: 2024.01.1-ndk
    
    steps:
      - checkout 
      - attach_workspace:
          at: ~/repo/tmp
      - android/restore-gradle-cache # restore deps and build artifacts
      - run:
          name: update gradlew permissions
          command: sudo chmod +x gradlew
      - android/run-tests:
          test-command: |
            ./gradlew testDebug
            ./tpm/cc-test-reporter format-coverage -t simplecov -o ./tpm/codeclimate.unittest.json coverage/unittest/.resultset.json
      - android/save-gradle-cache
      - run:
          name: Save unit test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  # for instrumentation tests
  android-test:
    <<: *default-keys
    parameters:
      system-image:
        type: string
        default: system-images;android-30;google_apis;x86

    executor:
      name: android/android-machine
      resource-class: large #change to xlarge if not enough/too slow
      tag: 2024.01.1-ndk

    steps:
      - checkout

      - run:
          name: update gradlew permissions
          command: sudo chmod +x gradlew
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: << parameters.system-image >>
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/outputs/androidTest-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  release-build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2024.01.1-ndk
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble release build
          command: |
            sudo chmod +x gradlew
            ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release

workflows:
  test-and-build-workflow:
    jobs:
      - setup
      - unit-test:
          requires:
            - setup
      - android-test:
          requres:
            - setup
          matrix:
            alias: android-test-all
            parameters:
              system-image:
                - system-images;android-30;google_apis;x86
                - system-images;android-29;google_apis;x86
                - system-images;android-28;google_apis;x86
                - system-images;android-27;google_apis;x86
                - system-images;android-26;google_apis;x86
                - system-images;android-26;google_apis;x86
                - system-images;android-26;google_apis;x86
                - system-images;android-26;google_apis;x86
          name: android-test-<<matrix.system-image>>
          filters:
            branches:
              only: main
    
      - release-build:
          requires:
            - unit-test
            - android-test-all # instrumentation tests ran on emulator
          filters:
            branches:
              only: main