version: 2.1

orbs:
  android: circleci/android@2.4.0


default-keys: &default-keys
  working_directory: ~/repo

  
jobs:
  setup-common:
    <<: *default-keys
    executor:
      name: android/android-docker
      tag: 2024.01.1-ndk
    steps:
      - checkout
      - run:
          name: Running check repo dir structure command
          command: ls -a

  unit-test:
    <<: *default-keys
    executor: # comes from the orb
      name: android/android-docker
      tag: 2024.01.1-ndk
    
    steps:
      - checkout
      - android/restore-gradle-cache # restore deps and build artifacts
      - run:
          name: update gradlew permissions
          command: sudo chmod +x ./GymTrackerApp/gradlew
      - android/run-tests:
          test-command: |
            ./GymTrackerApp/gradlew testDebug
      - android/save-gradle-cache
      - run:
          name: Save unit test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  # for instrumentation tests
  android-test:
    <<: *default-keys
    parameters:
      system-image:
        type: string
        default: system-images;android-30;google_apis;x86

    executor:
      name: android/android-machine
      resource-class: large #change to xlarge if not enough/too slow
      tag: 2024.01.1-ndk

    steps:
      - checkout

      - run:
          name: update gradlew permissions
          command: sudo chmod +x ./GymTrackerApp/gradlew
      - android/start-emulator-and-run-tests:
          test-command: ./GymTrackerApp/gradlew connectedDebugAndroidTest
          system-image: << parameters.system-image >>
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/outputs/androidTest-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  release-build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2024.01.1-ndk
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble release build
          command: |
            sudo chmod +x ./GymTrackerApp/gradlew
            ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release

workflows:
  test-and-build-workflow:
    jobs:
      - setup-common